using UnityEngine;

public class PlanetOrbit : MonoBehaviour
{
    // Gezegenin etrafęnda döneceđi merkez obje (Güneț)
    public Transform targetObject;

    // Yörünge hęzęnę belirler. Her gezegen için farklę olmalędęr.
    public float orbitSpeed = 10f;

    // Yörünge ekseni (Genellikle Y ekseni, yani Vector3.up)
    public Vector3 rotationAxis = Vector3.up;

    // Her oyun karesinde çađręlęr
    void Update()
    {
        if (targetObject == null) return; // Güvenlik kontrolü

        // Kendi objesini (gezegen) hedef objenin (Güneț) etrafęnda döndürür.
        transform.RotateAround(
            targetObject.position,
            rotationAxis,
            orbitSpeed * Time.deltaTime
        );
    }
}
